# Generated by Django 2.2.6 on 2021-03-09 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='website_name',
            new_name='group_name',
        ),
    ]
